### ISSUE TITLE
ventilationLevelTarget/set

### ISSUE THREAD

**Issue by Harri-V** [Jalle19/eda-modbus-bridge#53]
As far as I see, the ventilation level can not be set via mqtt. Can it be implemented?

I run the air conditioning by changing the target temperature and ventilation levels. At the moment I am using manual boost to raise the ventilation level for cooling, but it can only be set to last for 120 minutes.

**Comment by Jalle19** [comment]
It is unfortunately not possible to change the "normal mode" ventilation level via Modbus, only the target temperature. You can re-purpose e.g. the "Pitkään poissa" mode and set a ventilation level for that one. You can set "target temperature drop" to 0 degrees, but in my experience the minimum value is actually 2 degrees, so to maintain temperature while in "pitkään poissa" mode you have to simultaneously raise the main temperature target by two degrees.

I should probably document this since it's a big gotcha. I had to e-mail Enervent about it and they confirmed that it's not possible.
